# Spring Boot Application Name
spring.application.name=backend

# MySQL Datasource Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/AIChatbot
spring.datasource.username=root
spring.datasource.password=mysql

# Hibernate JPA
spring.jpa.hibernate.ddl-auto=update


gemini.api.key=AIzaSyCqfCOdCGRknUOnk__KZRx8JyyljXmOYcc

# Try option 1:
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemma-3-27b-it:generateContent

# Or option 2:
#gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemma-3-12b-it:generateContent